name: Deploy Service/Web App

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string


env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  # # SSH_CERT: ${{ secrets.SSH_CERT }}
  # SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:

  define:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Context
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    

      - name: Docker Context ls
        run: |
          echo ${{ env.SERVICE_NAME }}
          exit