name: Deploy Service/Web App

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string


env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  # SSH_CERT: ${{ secrets.SSH_CERT }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:

  define:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Context
        run: |
          touch rsa_id
          echo ${{ env.SERVICE_NAME }} > rsa_id
          chmod 600 rsa_id
          ls
          ssh -i rsa_id ops_admin@154.26.136.217 -p 33426
    

      - name: Docker Context ls
        run: |
          echo ${{ env.SERVICE_NAME }}