name: Deploy Service/Web App

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string


env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  # SSH_CERT: ${{ secrets.SSH_CERT }}
  # SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:

  define:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Context
        # run: |
        #   echo $SSH_KEY
        #   echo SSH_CERT
        # uses: arwynfr/actions-docker-context@v2
        # with:
        #   docker_host: 'ssh://ops_admin@154.26.136.217:33426'
        #   context_name: 'dev-server'
        #   ssh_cert: ${{ secrets.SSH_CERT }}
        #   ssh_key: ${{ secrets.SSH_KEY }}

      - name: Docker Context ls
        run: |
          docker service ls